# This is an example config file for the games-screenshot-manager.

# This option will run the program without actually downloading the files.
dry_run = false

# This option will specify the path to the output directory.
output_path = "Output"

# This section is used to configure the global settings for all providers.
# You can override these settings for each provider in each `providers` section.
[global]
# This option will enable/disable providers globally.
enabled = true

# This option will download the covers for the games.
download_covers = true

# This section is used to configure the gallery settings.
[gallery]
# This option will create a web gallery.
create = false

# This option will specify the title of the gallery.
site_title = "Games Screenshots"

# This section allows to specify context information for the gallery template.
[gallery.context]
# This option will specify the title of the gallery.
Title = "Games Screenshots"

# This option will specify the author of the gallery.
Author = "@fmartingr"

# This option will specify the URL of the gallery.
SiteURL = "http://screenshots.fmartingr.com"

# This option will specify the footer text of the gallery.
FooterText = "fmartingr's personal screenshot collection, copyright their respective companies. Be wary of spoilers!"

#
# Providers configuration
#

[providers.guild_wars_2]
# This option will enable/disable the provider.
enabled = false

# This option will specify the path to the screenshots folder.
# 'auto' will try to guess the path based on the platform.
path = "auto"

[providers.minecraft]
path = "auto"

[providers.playstation4]
# This option will specify the path to the screenshots folder.
path = ""

[providers.playstation5]
# This option will specify the path to the screenshots folder.
path = ""

[providers.steam]
# This option will specify the path to the Steam user data folder.
userdata_path = "auto"

# This option will enable/disable downloading screenshots from the Steam online gallery.
online_gallery = false

# This option will specify the Steam user ID.
user_id = ""

# This option will specify the Steam API key.
api_key = ""

# This option will specify names to use for games that are not in the Steam store.
# The key is the game ID and the value is the game name.
# This is useful for games that are not in the Steam store, like games you install on Steam to play with Proton.
[providers.steam.custom_games]
"1234567890" = "Custom Game"

[providers.world_of_warcraft]
# This option will specify the path to the screenshots folder.
path = "auto"

[providers.xbox_game_bar]
# This option will specify the path to the screenshots folder.
path = "auto"
